Fix failing smoke_test.py -  need to convert Unicode to ascii bytes for sending to socket.
  File ".../mcpi/connection.py", line 38, in send
    self.socket.sendall(s)
TypeError: 'str' does not support the buffer interface

George Hickman fixed this in https://github.com/py3minepi/py3minepi, but without adding
ascii to the codec.